### ISSUE TITLE
Performance, benchmarks, ...

### ISSUE THREAD

**Issue by dumblob** [ConorWilliams/libfork#1]
Hi, I've just discovered this potential gem. But to be sure the features reflect in practical setting, we'd need to test it first.

Do you have any such performance benchmarks (even if not rigorous...)?

I'd be mostly interested in direct comparison with [Nim's Weave](https://github.com/mratsim/weave/ ) which I myself consider as state-of-the-art library. So ideally the benchmarks could be aligned with Weave's ones :wink:.

Thoughts?

**Comment by ConorWilliams** [comment]
This and zero dynamic allocation are my top priorities, unfortunately I'm away from my desk for the next 3 weeks. I welcome any PR's

**Comment by dumblob** [comment]
Take your time - I'm also very busy, so don't expect any such well thought-through PR from me now :wink:.

**Comment by dumblob** [comment]
I just noticed a lot is going on in v2 branch.

Do you have any writeup about the goals and ideas for v2 (and why actually v2 and not improving v1 :wink:)?

**Comment by ConorWilliams** [comment]
Key changes are removing the global scheduler, allowing custom schedulers, allowing tasks to be run inline and overhaul of cmake+docs+benchmarks. Its semver so v2 as API break is required.

**Comment by dumblob** [comment]
Sounds great! Will keep an eye on the direction here. Feel free to ping me once there is something to publish :wink:.

**Comment by ConorWilliams** [comment]
Version 2 has released with benchmarks
