### ISSUE TITLE
Findhwloc CMake script not working

### ISSUE THREAD

**Issue by tzcnt** [ConorWilliams/libfork#13]
Your findhwloc CMake script doesn't work on my environment. I get this output:
```
[cmake] -- Could NOT find HwlocLibfork (missing: HwlocLibfork_INCLUDE_DIRS) (found suitable version "2.9.0", minimum required is "2.5.0")
[cmake] -- Found hwloc 2.9.0 in :hwloc
[cmake] CMake Warning at CMakeLists.txt:87 (message):
[cmake]   HWLOC not found, NUMA support disabled!
```
It seems to be failing to find the include file. I'm using Debian 12. My hwloc is installed as a system package, and the include file is in the most usual place...
```
➜  ~ ls /usr/include | grep hwloc.h
hwloc.h
➜  ~ sudo apt install libhwloc-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libhwloc-dev is already the newest version (2.9.0-1).
```
My [substantially less complex script](https://github.com/tzcnt/runtime-benchmarks/blob/main/cpp/1CMake/Findlibhwloc.cmake) seems to find the library and include file just fine.

**Comment by tzcnt** [comment]
For some reason PkgConfig is finding only the library and the version on my system, but not the include directory. By including a fallback to the `find_path` function for the individual missing elements (just the include path on my machine) I was able to get this working: https://github.com/tzcnt/libfork/commit/3655643a2b612817c16fc9abf99e6c8377cfb3bc

**Comment by ConorWilliams** [comment]
> For some reason PkgConfig is finding only the library and the version on my system, but not the include directory. By including a fallback to the `find_path` function for the individual missing elements (just the include path on my machine) I was able to get this working: [tzcnt@3655643](https://github.com/tzcnt/libfork/commit/3655643a2b612817c16fc9abf99e6c8377cfb3bc)

Nice find, I was scratching my head looking at this output!

**Comment by ConorWilliams** [comment]
Does #20 resolve this for you?

**Comment by tzcnt** [comment]
Works like a charm. I see that you were able to remove the Boost dependency as well. Nice work!

**Comment by tzcnt** [comment]
Works like a charm. I see that you were able to remove the Boost dependency as well. Nice work!
