### ISSUE TITLE
Update the doctest version in /test/CMakeLists.txt

### ISSUE THREAD

**Issue by ccjeff** [ConorWilliams/libfork#2]
Hi, when I'm trying to compile the program, I was having the same issue as mentioned in [Can't compile with glibc master (future 2.34): SIGSTKSZ is no longer a constant](https://github.com/doctest/doctest/issues/473). I was trying to update the doctest version into `2.4.6` but was having this error: 
<img width="641" alt="image" src="https://user-images.githubusercontent.com/46590685/202871459-ab8344d9-3694-4b01-aca3-7868f4a38b9c.png">

Would appreciate it very much if anyone can give me some advice on how to fix this. Thanks!

**Comment by ccjeff** [comment]
Ok...It seems like it's still a doctest's problem, change the version to `2.4.8` solves the problem but after fixing the compile problem, the example tests failed with segfault

**Comment by ConorWilliams** [comment]
Thanks for writing this up, will have a look at it when I get the chance

**Comment by ConorWilliams** [comment]
Version 2.0 has moved to Catch2 (v3) which compiles much faster as it is not header only
