### ISSUE TITLE
macOS 14.5: "hwloc's cpu binding is not supported on this system"

### ISSUE THREAD

**Issue by stephenberry** [ConorWilliams/libfork#23]
This library looks really nice. I'm trying to use it with Xcode 15.4, but I hit the following error:

```c++
 case ENOSYS:
          LF_THROW(hwloc_error{"hwloc's cpu binding is not supported on this system"});
```

I'm using `lf::lazy_pool pool(4);`

**Comment by ConorWilliams** [comment]
A shame this is not supported on Mac, you can disable hwloc support to stop this error but then libfork will not be numa aware

**Comment by ConorWilliams** [comment]
Pass `-DLF_NO_HWLOC=On` to the configuration step

**Comment by stephenberry** [comment]
Thanks, yeah I found that option and was able to run without `hwloc`. I'll close this as it's not an issue for me anymore. Thanks!

**Comment by ConorWilliams** [comment]
Fantastic, I think upstream is tracking this: https://github.com/open-mpi/hwloc/issues/555
